version: '3'
services:
  proxysql:
    build: .
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: backend
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
